name : Backend CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name : checkout source code
        uses : actions/checkout@v5

      - name : setup java 21
        uses : actions/setup-java@v5
        with :
          java-version : "21"
          distribution : "temurin"
          cache : maven

      - name : Build and test
        run : ./mvnw clean verify

      - name : Build docker image
        run : docker run -t studysync-backend:${{github.sha}} .